import Head from "next/head";
import { useState } from "react";
import styles from "../styles/Home.module.css";

export default function Home() {
  const [mouseOver, setMouseOver] = useState(false);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <svg
        xmlns="http://www.w3.org/2000/svg"
        width="345"
        height="345"
        fill="none"
        viewBox="0 0 345 345"
        onMouseEnter={() => setMouseOver(true)}
        onMouseLeave={() => setMouseOver(false)}
      >
        <path fill="#E5E5E5" d="M0 0H345V345H0z"></path>
        <g>
          <path
            fill="#fff"
            d="M0 0H1440V1024H0z"
            transform="translate(-547 -340)"
          ></path>
          <g>
            <circle cx="172.5" cy="172.5" r="172.5" fill="#5B82E8"></circle>
            <circle cx="137.5" cy="145.5" r="16.5" fill="#000"></circle>
            <circle cx="203.5" cy="145.5" r="16.5" fill="#000"></circle>

            {mouseOver && (
              <path
                stroke="#000"
                strokeLinecap="round"
                strokeLinejoin="round"
                strokeWidth="10"
                d="M116 209c37.5 36 63.5 38 114 0"
              ></path>
            )}

            {!mouseOver && (
              <path
                stroke="#000"
                strokeLinecap="round"
                strokeLinejoin="round"
                strokeWidth="10"
                d="M115 237c48.418 2.776 75.515 1.437 114 0"
              ></path>
            )}
          </g>
        </g>
      </svg>
    </div>
  );
}
